
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int AND = 12;
  public static final int INTEGERS = 26;
  public static final int SEMICOLON = 17;
  public static final int CLASS = 3;
  public static final int PLUS = 8;
  public static final int RPAREN = 16;
  public static final int SYMBOL = 25;
  public static final int IDENTIFIER = 23;
  public static final int PERIOD = 22;
  public static final int RCURLYBRACKET = 19;
  public static final int LBRACKET = 20;
  public static final int LPAREN = 15;
  public static final int PUBLIC = 4;
  public static final int RBRACKET = 21;
  public static final int STATIC = 5;
  public static final int EOF = 0;
  public static final int PRINTLN = 14;
  public static final int MAIN = 7;
  public static final int MINUS = 10;
  public static final int LCURLYBRACKET = 18;
  public static final int error = 1;
  public static final int DISPLAY = 2;
  public static final int INTEGER = 24;
  public static final int VOID = 6;
  public static final int BECOMES = 9;
  public static final int LESS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "PLUS",
  "BECOMES",
  "MINUS",
  "TIMES",
  "AND",
  "LESS",
  "PRINTLN",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LCURLYBRACKET",
  "RCURLYBRACKET",
  "LBRACKET",
  "RBRACKET",
  "PERIOD",
  "IDENTIFIER",
  "INTEGER",
  "SYMBOL",
  "INTEGERS"
  };
}

